record:
  first_frame: 1
  last_frame: 100
  skip_frames: 20
  input_dir: "/data/develop/calib_k4a/recordings"
  feeds:
    - "cn01/capture-000000.mkv"
    - "cn02/capture-000000.mkv"
    - "cn03/capture-000000.mkv"
    - "cn04/capture-000000.mkv"
  output:
    # - timestamp
    # - depth
    # - color
    - infrared
    # - rgbd
    #- pointcloud
    # - align_clouds 
  output_dir: "../export_calib"
timesync: true
seek: false
