record:
  first_frame: 1
  last_frame: 100
  skip_frames: 20
  input_dir: "/storage/calib_4k/"
  feeds:
    - "cn01/capture-000000.mkv"
    - "cn02/capture-000000.mkv"
    - "cn03/capture-000000.mkv"
    - "cn04/capture-000000.mkv"
  output:
    # - timestamp
    # - depth
    - color
      # - rgbd
      #- pointcloud
      # - align_clouds 
  output_dir: "../export_calib"
timesync: true
seek: false
