mode: PCPD
record:
  start_ts: 1000
  end_ts: 5000
  skip_frames: 1
  input_dir: "/storage/atlas_recordings/210810_animal_trial_01/recordings/recordings_1108_recording_5/"
  feeds:
    - "cn01/"
    - "cn02/"
    - "cn03/"
    - "cn04/"
  output:
    # - timestamp
    # - color
    # - depth
    #    - infrared
    # - rgbd
    - pointcloud
    - align_clouds
  output_dir: "/storage/holistic_or/holistic_or_take_2_pointclouds"
timesync: true
seek: false
