record:
  first_frame: 500 
  last_frame: 8000
  input_dir: "/storage/holistic_or"
  feeds:
    - "cn01/capture_cn01_take2.mkv"
    - "cn02/capture_cn02_take2.mkv"
    - "cn03/capture_cn03_take2.mkv"
    - "cn04/capture_cn04_take2.mkv"
    - "cn05/capture_cn05_take2.mkv"
    - "cn06/capture_cn06_take2.mkv"
  output:
    - timestamp
    - color
    - depth
      #    - infrared
    - rgbd
      # - pointcloud
    - fused_pointcloud
  output_dir: "../export_take_2"
