record:
  first_frame: 1000
  last_frame: 3000
  skip_frames: 10
  input_dir: "/storage/holistic_or_export/"
  feeds:
    - "cn01/capture_3.mkv"
    - "cn02/capture_3.mkv"
    - "cn03/capture_3.mkv"
    - "cn04/capture_3.mkv"
    - "cn05/capture_3.mkv"
    - "cn06/capture_3.mkv"
  output:
    # - timestamp
    - depth
    - color
      # - rgbd
    - pointcloud
    - align_clouds
  output_dir: "../test_system"
timesync: true
seek: false
