record:
  first_frame: 0
  last_frame: 20
  skip_frames: 1
  input_dir: "/storage/holistic_or/"
  feeds:
    - "cn01/capture.mkv"
    - "cn02/capture.mkv"
    - "cn03/capture.mkv"
    - "cn04/capture.mkv"
  output:
    # - timestamp
    # - depth
    # - color
    # - infrared
    # - rgbd
    - pointcloud
    # - align_clouds
  output_dir: "../output"
timesync: true
seek: false
