record:
  first_frame: 1000
  last_frame: 4000
  skip_frames: 10
  input_dir: "//artekmed/recordings/03_animal_trials/210914_animal_trial_03/recordings/recordings_1409_recording_05/"
  feeds:
    # - "cn01/capture-000000.mkv"
    - "cn02/capture-000031.mkv"
      # - "cn03/capture-000000.mkv"
      # - "cn04/capture-000000.mkv"
  output:
    # - timestamp
    # - depth
    - color
      # - rgbd
      # - pointcloud
      # - align_clouds
  output_dir: "~/ownCloud/atlas/scene_export_2109/suture/"
timesync: true
seek: false
