mode: PCPD
record:
  start_ts: 1632804955682321998
  end_ts: 1632805075983893801
  skip_frames: 10
  max_frame_count: 10000
  input_dir: "/media/storage/atlas_recordings/recordings_2809_recording_2"
  feeds:
    - "cn01/"
    - "cn02/"
    - "cn03/"
    - "cn04/"
  output:
    # - timestamp
    - color
      # - color_video
    # - depth
    # - infrared
    # - rgbd
    # - pointcloud
    # - align_clouds
    # - bodypose
  output_dir: "/media/storage/atlas_export/"
timesync: false
seek: false
