mode: PCPD
record:
  start_ts: 1637639393835000000 
  end_ts: 1637639483132000000
  skip_frames: 5
  max_frame_count: 500
  input_dir: "/mnt/recordings/03_animal_trials_to_upload/211123_animal_trial_11/recordings/recordings_2311_recording_01/"
  feeds:
    - "cn01/"
    - "cn02/"
    - "cn03/"
    - "cn04/"
  output:
    - timestamp
    - color
    # - color_video
    # - depth
    # - infrared
    # - rgbd
    # - pointcloud
    # - align_clouds
    # - bodypose
  output_dir: "/archive/230123_pointcloud_export/"
timesync: true
  # override_timestamps: true
seek: false
