mode: PCPD
record:
  # start_ts: 1632804955682321998
  # end_ts: 1632805075983893801
  skip_frames: 5
  max_frame_count: 50
  input_dir: "/mnt/atlas_1/03_animal_trials/211102_animal_trial_08/recordings/recordings_0211_recording_01/"
  feeds:
    - "cn01/"
    - "cn02/"
    - "cn03/"
    - "cn04/"
  output:
    - timestamp
    - color
    # - color_video
      # - depth
    # - infrared
    # - rgbd
    - pointcloud
    # - align_clouds
    # - bodypose
  output_dir: "/data/atlas_export/"
timesync: true
seek: false
